/**
 * Daily Briefing — deterministic generated ops summary with copy-out.
 */

import { useMemo, useState } from 'react';
import { generateDailyBriefing } from '../lib/analytics.js';
import { useAppState } from '../AppState.jsx';
import { Card, Badge } from './ui.jsx';

function briefingToText(b) {
  const lines = [`DAILY BRIEFING — ${b.date}`, b.headline, ''];
  for (const s of b.sections) {
    lines.push(`## ${s.heading}`);
    for (const bullet of s.bullets) lines.push(`- ${bullet}`);
    lines.push('');
  }
  lines.push('— Generated by Warehouse AI People Command Center (rule-based, aggregate data only)');
  return lines.join('\n');
}

export default function DailyBriefing() {
  const { dataset } = useAppState();
  const { locations, cohorts, festivals } = dataset;
  const [copied, setCopied] = useState(false);

  const briefing = useMemo(
    () => generateDailyBriefing(locations, { cohorts, festivals }),
    [locations, cohorts, festivals],
  );

  const copy = async () => {
    try {
      await navigator.clipboard.writeText(briefingToText(briefing));
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch {
      setCopied(false);
    }
  };

  return (
    <div className="space-y-6">
      <Card
        title={`Daily Briefing — ${briefing.date}`}
        subtitle="Auto-generated from today's data · deterministic and auditable"
        actions={
          <div className="flex items-center gap-2">
            <Badge tone={briefing.headline.includes('critical') ? 'critical' : 'good'}>
              {briefing.headline.includes('critical') ? 'action needed' : 'stable'}
            </Badge>
            <button
              type="button"
              onClick={copy}
              className="rounded-lg border border-slate-600 px-3 py-1 text-xs text-slate-300 transition hover:border-slate-400"
            >
              {copied ? 'Copied ✓' : 'Copy text'}
            </button>
          </div>
        }
      >
        <p className="mb-5 rounded-lg border border-slate-700 bg-slate-800/40 p-3.5 text-sm font-medium text-slate-100">
          {briefing.headline}
        </p>
        <div className="grid gap-4 lg:grid-cols-2">
          {briefing.sections.map((s) => (
            <div key={s.heading} className="rounded-xl border border-slate-700/60 bg-slate-900/60 p-4">
              <h3 className="mb-2.5 text-xs font-semibold uppercase tracking-wider text-sky-300">{s.heading}</h3>
              <ul className="space-y-2">
                {s.bullets.map((b, i) => (
                  <li key={i} className="flex gap-2 text-[13px] leading-relaxed text-slate-300">
                    <span className="mt-1.5 h-1 w-1 shrink-0 rounded-full bg-slate-500" />
                    {b}
                  </li>
                ))}
              </ul>
            </div>
          ))}
        </div>
      </Card>
    </div>
  );
}
